apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-friends-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "RSS订阅"
    rbac.authorization.halo.run/display-name: "RSS订阅查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:friends:view"]
rules:
  - apiGroups: [ "friend.moony.la" ]
    resources: [ "friends" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-friends-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "RSS订阅"
    rbac.authorization.halo.run/display-name: "RSS订阅管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:friends:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-friends-view"]
rules:
  - apiGroups: [ "friend.moony.la" ]
    resources: [ "friends"]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]