apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-friends-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: '友链朋友圈'
        - $formkit: code
          name: menu_html
          label: 菜单
          height: 200px
          language: html
          value: <li> <a href="/friends" title="首页"> <span>首页</span> </a> </li>
                <li> <a href="/blogs" title="博客广场"> <span>博客广场</span> </a> </li>
                <li> <a href="/blog-requests/add" title="提交博客"> <span>提交博客</span> </a> </li>
                <li> <a href="/blog-requests" title="审核结果"> <span>审核结果</span> </a> </li>
        - $formkit: text
          label: 朋友圈列表显示条数
          name: pageSize
          validation: required|Number
          value: 10
        - $formkit: group
          name: gravatar
          label: 头像 Gravatar
          help: "用户提交，邮箱自动匹配头像"
          value:
            apiUrl: https://cravatar.cn/avatar/
            apiParam: d=mp&s=80
          children:
            - $formkit: text
              name: apiUrl
              label: API地址
              help: "后缀带 /"
              validation: required
            - $formkit: text
              name: apiParam
              label: API参数
              validation: required
        - $formkit: group
          name: email
          label: 邮件通知
          value:
            sendEmail: false
          children:
            - $formkit: radio
              name: sendEmail
              id: sendEmail
              label: 是否发送邮件通知
              value: false
              options:
                - value: true
                  label: 开启
                - value: false
                  label: 关闭
            - $formkit: text
              if: "$get(sendEmail).value === true"
              name: adminEmail
              label: 管理员邮箱
              help: 管理员邮箱，用于接收邮件通知
              validation: email
            - $formkit: text
              if: "$get(sendEmail).value === true"
              name: domain
              label: 本站域名
              help: 填写站点域名，如：moony.la
